kind: pipeline
type: exec
name: ccc-ssh

steps:
- name: build-staging
  commands:
    - docker stack deploy -c stack-staging.yml --with-registry-auth ccc-hr-core-staging

  when:
      # event: push
      branch: staging
      
- name: build-production
  commands:
    - ls 
  when:
      # event: push
      branch: master
