kind: pipeline
type: exec
name: ccc-ssh

steps:
- name: test-dev
  commands:
    - hostnamectl
    - pwd
    - . /home/ubuntu/docker.sh 
  when:
      # event: push
      branch: develop

- name: build-staging
  commands:
    - hostnamectl
    - . /home/ubuntu/docker.sh 
    # - docker stack deploy -c stack-staging.yml --with-registry-auth ccc-hr-core-staging

  when:
      # event: push
      branch: staging
      
- name: build-production
  commands:
    - ls 
  when:
      # event: push
      branch: master
