FROM php:7.2-fpm
RUN sed -i 's/9000/3002/' /usr/local/etc/php-fpm.d/zz-docker.conf

COPY . /var/www/html
ADD .env.docker.local /var/www/html/.env

WORKDIR /var/www/html

COPY composer.json composer.json
COPY composer.lock composer.lock

# Install Additional dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Add and Enable PHP-PDO Extenstions
RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-enable pdo_mysql
RUN docker-php-ext-install bcmath

RUN chmod -R 777 storage
RUN chmod -R 777 bootstrap/cache

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer install --no-scripts
RUN composer update

RUN php artisan install
RUN php artisan storage:link

RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

EXPOSE 3002
CMD ["php-fpm"]
