FROM hr-staging AS PHP

FROM nginx:alpine

WORKDIR /var/www/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx-prod.conf /etc/nginx/conf.d

COPY --from=PHP /var/www/html .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]