version: "3.3"
services:
  php:
      image: registry.gitlab.com/ccc-hr/core:staging
      networks:
        - hr-net
      volumes:
        - storage:/var/www/html/storage
      environment:
        - SET_CONTAINER_TIMEZONE=true
        - CONTAINER_TIMEZONE=Asia/Jakarta
      deploy:
          restart_policy:
            condition: on-failure
          placement:
            constraints:
              - node.hostname == hr
  nginx:
      image: nginx-php
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - storage:/var/www/html/storage
      networks:
        - hr-net

volumes:
  storage:

networks:
  hr-net:
    driver: bridge